#!/usr/bin/env bash
# Generate strong random secrets into backend/.env for local compose runs.
#
#   ./scripts/gen-secrets.sh          # writes .env (refuses to overwrite)
#   ./scripts/gen-secrets.sh --force  # overwrites an existing .env
#
# The compose file reads JWT_SECRET / ENCRYPTION_KEY from .env, so `docker
# compose up` after this never runs with known placeholder secrets. Production
# must still set real secrets in the cluster (see deploy/k8s/secret.example.yaml).
set -euo pipefail

cd "$(dirname "$0")/.."
DOTENV=".env"

if [[ -f "$DOTENV" && "${1:-}" != "--force" ]]; then
  echo "error: $DOTENV already exists (use --force to overwrite)" >&2
  exit 1
fi

JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n=')"
ENCRYPTION_KEY="$(openssl rand -base64 32 | tr -d '\n')"

cat > "$DOTENV" <<EOF
# Generated by scripts/gen-secrets.sh — DO NOT COMMIT. Override with your own
# values in real environments.
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
EOF

echo "wrote $DOTENV with fresh secrets (JWT_SECRET ${#JWT_SECRET} chars, ENCRYPTION_KEY ${#ENCRYPTION_KEY} chars)"
