// Package docs is generated by `swag init -g cmd/server/main.go`.
// The placeholder spec is replaced by running `make swagger`.
package docs

import (
	"github.com/swaggo/swag"
)

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "AeroXe DocuFlow digital document management API. All endpoints use POST/PATCH/DELETE with JSON bodies; pagination is cursor based. Run 'make swagger' to regenerate this spec from annotations.",
        "title": "AeroXe DocuFlow API",
        "contact": {},
        "version": "1.0.0"
    },
    "host": "localhost:8080",
    "basePath": "/",
    "paths": {},
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

var swaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AeroXe DocuFlow API",
	Description:      "AeroXe DocuFlow digital document management API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(swaggerInfo.InstanceName(), swaggerInfo)
}
